name: Test Runner Labels

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [Linux]
    runs-on: ["${{ matrix.os == 'Linux' && 'ubuntu-latest' || 'windows-latest' }}"]
  
    steps:
      - uses: actions/checkout@v3

      - name: Print GitHub CLI version
        run: gh --version

      - name: Create PR
        id: pr-created
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          pr=$(gh pr create --title "Test PR" --body "Testing Only." --base main --head atai-test | tail -1)
          echo "pr_number=${pr##*/}" >> $GITHUB_OUTPUT

      - name: Print PR number
        run: echo ${{ steps.pr-created.outputs.pr_number }}
