name: Test Runner Labels

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [Linux, Windows]
    runs-on: ["${{ matrix.os == 'Linux' && 'ubuntu-latest' || null }}", "${{ matrix.os == 'Windows' && 'windows-latest' || null }}"]
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
