name: Test Runner Labels

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [Linux, Windows]
    runs-on: ["${{ matrix.os == 'Linux' && 'ubuntu-latest' || 'windows-latest' }}"]
  
    steps:
      - uses: actions/checkout@v3

      - name: Print GitHub CLI version
        run: gh --version
